### ISSUE TITLE
Configuration options for autoscaling

### ISSUE THREAD

**Issue by mismosmi** [philibea/scaleway-containers-deploy#23]
Hi,
we are looking into vercel-style preview deployments on scaleway and it would be really cool to be able to configure some more scaling options through this action, particularly useful would be
* min and max instance count
* cpu
* concurrent connections

would it be possible to make those configurable?

**Comment by philibea** [comment]
Hello @mismosmi, i will check if it's possible to add everything. Actually i add min and max instance count.

**Comment by mismosmi** [comment]
Oh sweet, i did not expect this at all

Instance count is already 99% of the way because we use preview deployments that could easily save cost by scaling to zero.
